# Generated by Django 5.2.5 on 2025-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
